### PR TITLE
Problem 3

### PR DESCRIPTION
**Pull request by AtharvaK-15**
Solved problem using nltk library in python. Made an API using FASTAPI and hence using these the prompt text gets optimized as the token count gets reduced.

### CODE REVIEW

**Comment by anubrag** [comment]
removing stopwords is a good first step. What are some other things you can do ?

**Comment by AtharvaK-15** [comment]
> removing stopwords is a good first step. What are some other things you can do ?

Other than removing stopwords, we can reduce the size of the prompt text using Text Summarization in NLP. Do you want me to implement that as well?

**Comment by anubrag** [comment]
Yes but make sure the meaning and context of input stays the same

**Comment by AtharvaK-15** [comment]
> 

Hey so I tried to work on text summarization, but I'm not able to parse that data through API just like I did with my last commit. However it works in the terminal.

**Comment by anubrag** [comment]
Hey, congratulations on completing this assignment successfully! Please visit this link for next steps: https://www.notion.so/zenop/Final-Round-of-the-Interview-Outcomes-and-Next-Steps-36f66c7579cc424f9848c7f3243f99b3

**Pull request closed without merging**
